baseurl = "/"
languageCode = "en-us"
title = "Ase Flex network 1 study blog"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 6
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
enableRobotsTXT = true



[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Stefano Fenili"
    bio = "Network Engineer"
    location = "Earth"
    site_description = "HP Ase - Flex network 1 study blog is my personal study blog  to help me to prepare ASE certification.  "
    copyright  = "Stefano Fenili, Powered by [Hugo](//gohugo.io)."
    avatar = "https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/3/005/088/002/126d0ef.jpg"
    logo = "http://www.www8-hp.com/it/it/images/i/hpi/header-footer/caas-hf-v3.2/hpi-hp-logo-pr.gif"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"


# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/digitalcraftsman"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "Magy"
    gitlab          = ""
    bitbucket       = "sfenili"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "ilmagy"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "stefanofenili"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "stefano.fenili"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = true
